tasks:
  - init: echo "Locate TOMCAT SERVERS, press the + sign and navigate to /tmp, select tomcat 9 folder."
    command: echo "Then, run cd ./aps-webdev && mvn package, then go to target folder, right-click aps-webdev.war and select run with tomcat server.
      Then click "make public" and then "open browser" when prompted."
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - vscjava.vscode-java-pack@0.9.0:70x0ZBbqBMOBNXgG3kqVSw==
    - adashen.vscode-tomcat@0.11.1:qq+mWSZCHkrza2mPgOhorg==